- hosts: web
  tasks:
  - name: "sync the website"
    synchronize:
      src: siteThatHostsTheOneFile/
      dest: /var/www/{{ domain }}
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no
